# STRONGBOX ENCRYPTED RESOURCE ; See https://github.com/uw-labs/strongbox
pTNhEo7JCyXma5DR1/f1ShNiT+/Kvz0T8f5Wi3dB4YVNKZ0Y4Tm03havOv3DBelaPU5FkYD5HP7N
YPzOlf/sIajR4A6+u4hfA0v1cRKjJdgh62JOz251hnPKmhj2zx2ZeoytCd/DcRx/juQ1cyNCw4bN
9CcGxOgyz4JhD7Mu/n8dXdq4C+bJNt8dtyqVf8m+KuF9QJhQYnmJ3ptqasRtoB5HLBGaYlkXeBtD
s/AzT5hBao9NcGkr1MLunDUNk49Tzjgp0Z6TzfIF/1sKJr2/yr1sTEJyiRFozRt8w+vCBNi3d4XY
4XnytE4NijmyTAVNo5MXIs2tVQVd7q8AwiXWXCw0lRxnbs9Lr4k+3uDAlhE6jyMawXVlyBYob1sx
x61NY+HiZ6FlN/rtRsk888sSi5WvRap6H0TAEFNe4BsfUe+Sfn3AePW7dPO4QB/eHeZ5Cs/iDhRe
XnfvQ8W+WtZMHnFOuN+TtWgflZHow+22/+0cLqgTnW9NsPmplzSQMw21Nz9AMTLnQyKMDPXOBcKx
CRjaL3Ohvk5Hzg1Yp+ZSj5LVzDLidaFIEXgEQgqYD0Sv6ZPvsu525D80zCVQhSJoL3UE10m5c+Fn
fFZ40KUO0UZgc7vxGdYZ9jiAScqZTDQHP5TrZXxUxgXj1Z2/a8zGj2zXKQAW7w8dZ5cPtOUAG8oN
o4pxtM5i1hyCxqMKRiSEiqgKFK+77QxC+o8rjbbI0yVjX2mFTrVVs2D2AMtWGJ806ZubmcEnLZyY
IPqzswtrK1WKMSVGBukHvBttaYl8bpeGrLgn2+18Vo5Mykv6aTH/Bchbb2RZKKe/lZ4RBA1li++E
jUtmp6oX8eQYtXmaryOCiHggskmX937I49LVCic0OPJ8ZSsLoIgNRPQ3Osz+8cp2ygsGDyOfdEKo
yvfOw5liiVW4z8BlrP6QnEH33HMW8lIU0fCn5jNFIdkpDpVEuscp26EDl8eonmGk2oFtGWDBx/he
2JvrugN6dYJaqq8J5gVSFWjThFxX4WgRu99kchiCn22SR3qroz0vwSrtcMqbTeMXDBr499KDhmYT
cKQxT9ngwgBaAnj1AWhmfkU889KUL3Z7HxwuPLUzgb2CQVdTA5Vy4W7MfJUKFJV63yJ5IW1SgHMr
/BOlumMH2pbYxnnJz/fZIEg6LUy0Y3BfyZJXHw11pSoQRAG0cqIExWRfRmX/ONFlPxOhRsygZfhD
cbXhmI26cZgQvCLxj3TpXZtqQHf22yFPf/Z0utI5iJi7gr2q97M9734YHAfcwFfU7+GN9CoI+9hd
OkQALGhoo8RSc/QRTp0WLQfspGg+glvh6TJ6vA0iT2QvxRCFSjgyYRphfHPRt2H9b3O41yuHQDtO
jBLyMdzGFnqa5C6/wpZNG1gA/Yx+yA1s6p1+31FOg+12svrt3NrmjBUwkfD5AtqkjA3/wX5XYuuB
QnLBInHIj9ZQiv+7ZMWP3fli6MnGLf++yFZ6J4uPmZqKToGfwiOBWwkXiKztes4Bel2v5vRkq2++
cvZsHPoLKGxpCFMoRMlsiLwrMCbnZst4uTB/1QqE1HNBAvi/oHa7esR7y17zw/32PQhBiVi4emCB
4Na0Ho9OAFdMzxgaA7n1I+nw9c0IttGCz/MWLjL27Wiuaqk374o+mpm1srs7HWYO6lobX0bc+RvV
9VyTjI8q4XP7X5dx6zMo4fT9Ck6KrMZ+Z5tjG4lAkLx+EhpptAjvhCk3a51Nxf5WVv7UymlJ18c2
xO+itB58ZG3Qe7Vyax+PBe8VwQU8RuuqWFRbzq2OepNPhu01g78kiLbSHOoddQixo4UbqyaODusX
SCWt/M90lXLf0ExmMvrDldG4JmH9ccaCDMzs480qepLp91mdzT4qLu80TFTucm/ui5cPLKdsDJLH
Am8yeujz0oVPqcLCqVDfZtW28BwVYF2k1vNuiZQDpdbSJ5bHf2DMQbV+6RRlM8svQS25513GhXIs
dhT/Z9MIGD+ZC7PS8MTYHGEPKrj4P98NeEvuPTYGK1GKHdS+zwbMCGIIcBcEx2Jn/soYKu4xVAZn
H1QH8R2G+zC6JwcdyhFnP8ayjK5kKvXeTEDEk5eNDJwDqmwYN/9dF0s=
