# STRONGBOX ENCRYPTED RESOURCE ; See https://github.com/uw-labs/strongbox
pQ85UKHHoAjJGeDvdU1Fs3RL42oKcTiovIDb3quw83Rm1atkaErY4KewiwmzR5NTffdUgs0BGaoI
Gehk6+R3guMTs9oGgTV4tRV+aJGFlPEEoku/IZhKA2nNDK08vO1HecGkkvmcxOZC05GEY07/YNuD
87iBzmGlrqDnaSM/GsFhU8RPeiVGH3mwDaHzvee/HAgHHe9WbXusGipA42dOu/Q2j8J4kvo/tcm3
dtsW8U7bn0o0QEKNmJQ0cD3HVgm7PLb4TN3SkOphDYHPQwwBNVF2UzPZANHDCp3LKha0WlC7/tZ5
DShLdFplse9dHwINRjthRRnIC7Fw5ErgHkSh/BpTiAp7mOtR2eUqet9Zv3MF5nCFQULbubUsn8RL
s+nVoD2q2GYs81Eax+vN3okW0BefL9Lj6z886FSifoFer7HFFcbS//x3OCd9NBcPUMUDTBTHTE1S
8Z/OUKilzFIBkESR8X+fbqChDP6mX6hH4dtD6GG6yxLyQ2nQAkjpbjzGbNrQYiB1vhsw9CNG9g+g
jmEzrFmliqw/MhfbLaswYmK2qTjamAAD8hHzVtpVTN+eHhOtrTG8q1I8fGBmayVdFIWYqcidkKo9
wTg9winnRtZDtPP+Sh3W7XZ0LiWbkXYecJ1Bugpbzssb/CYerOYvi6DoicQRW8Di0XleWaB+tBER
GYHHG7XJbUzuJjXtmvj7iFbkJyoXSGg74AgEqwAduY8hHCy1/sntNz0u6VmaHGdVx25QXeK7Dwmw
SBcinDd1cp1ubORMbgzzGSQ6ERHtFoGKFJT9OQnjAXUh6tnSd7JKAQfwjFmxd2ZJXAGDL1Es69Kg
+0Ac98z70CRrLueFX6Rcao1uedlAIPZtJ6k7nIHfWM4xl4um4DSoeQIO7xHCbDy9nXVIxR9hEmsH
ymFRaw7WwWogclEdZ8qOtwCJ4qaswFMDAGQG0q3dQqjetONDSWtWzmQP7IOQ9BMAhm3tojRB487E
0cJvwmFg4Diq8dRPADBqEFq245Vl0tr+v3FWOJgOcX2jx33qRSqlXh0CQ+N6QKHYXNqYLKN8PSjM
pAggynYBxWBRINq39Q2frS1zFjAep6l+ULzbx1+/4dn+8BlFwc0vBrM8RM4MayT8+5FkBkHZqmEd
2ZNxShXX1X1UiT/dTsVyDcHqgq3yxoEZ9o0r3pI+IN/OwrM9kUE4wWvtRXrmkKfNehAip3GNLVE2
p8Lt07OFTB7SQ1cWS6pQ1o1j1rWPjk9BoXFHmllR1HXwT519yzTcO2OnQjCFT3kq8NhAtE0utQQE
sq/ebxn0hD9v659CO2VwgZu6LRCo7PuHtFSle3ZlWMFGe3glryTEuSXXMoFARaAeHYiTXT7c1de3
3+6mm6QmZk4qEpIh2MmToMouk5yCc3GaisVtJwrxB7waJ82LBVNAUBCHZRx0mBdRMfjOh68eYStH
whIZ/EE48kAdBy1n5zmlbpL/TynxDz4DqspUg8T9GVEMO5KJG0fH0X+sBrzf6rarQNgQWQk9OFVI
97i2ddN5xQpn7z6G56tGIG0FsH+MimXmzy5o+QSvIH9yx08MiKyb3/GxmMNmo/9nTFnaHx7CRL30
HMi9DASQ4mIeAkaykJrthT3aVReAkuXuJxWo6g4XkDQFF0lL/EDvB3zrJJPzsDt88AFa6FOi64Qp
iAe0hqk4cToTxSx70ojlKKkjWrJmJrDdnp12xFhWTol9soKJyadMa46VlmkMR3d6DsTu5K+0PGyj
vkSsHXTopR83iE5a+OyrGlss0GReYX+bq2CF/spf9Gz/bgh6NhzqSOyev1HkDKugwY61+6kyekL1
VVwkxyoiD+X0ow0kio2P86c5Jcfnf6kRGC+96TNbjvsY7ov+QzgmOvuH2uObQG/YzP/QSL0xgltp
EDmao/p7gG5vppa8ush+BHlWjtlZoxjg0c+1ehiiuTjPsCdAUbwtl+vqCvhg/nNukGc1t1LJRY/9
cysXxzxV272R6Qo7LPmwHMoDzEAh4qVLU9WZfdOJkOLnYfmAhu1c4nGgIgPXQRcoaA==
