---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Events
- type: directory
  path: suyamSite/content/english/events
  label: Events (en)
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Organisation
- type: directory
  path: suyamSite/content/english/organisation
  label: Organisation (en)
  create: documents
  match: "**/*"
  templates:
  - organisation
- type: heading
  label: Projects
- type: directory
  path: suyamSite/content/english/projects
  label: Course (en)
  create: documents
  match: "**/*"
  templates:
  - projects
- type: heading
  label: Activities
- type: directory
  path: suyamSite/content/english/activities
  label: Activities (en)
  create: all
  match: "**/*"
  templates:
  - activity
- type: heading
  label: Awards
- type: directory
  path: suyamSite/content/english/awards
  label: Awards (en)
  create: all
  match: "**/*"
  templates:
  - awards
- type: heading
  label: Event
- type: directory
  path: suyamSite/content/english/event
  label: Event (en)
  create: all
  match: "**/*"
  templates:
  - event
- type: heading
  label: Donate
- type: directory
  path: suyamSite/content/english/donate
  label: Donate (en)
  create: all
  match: "**/*"
  templates:
  - donate
- type: heading
  label: Volunteers
- type: directory
  path: suyamSite/content/english/volunteers
  label: Volunteers (en)
  create: all
  match: "**/*"
  templates:
  - volunteers
- type: heading
  label: Gallery
- type: directory
  path: suyamSite/content/english/gallery
  label: Gallery (en)
  create: all
  match: "**/*"
  templates:
  - gallery
- type: heading
  label: Others Pages
- type: directory
  path: suyamSite/content/english/about
  label: About (en)
  create: none
  match: "*"
- type: directory
  path: suyamSite/content/english/contact
  label: Contact (en)
  create: none
  match: "*"
- type: directory
  path: suyamSite/content/english/pages
  label: Created Pages (en)
  create: documents
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: suyamSite/content/english
  label: All Pages (en)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Data
- type: directory
  path: suyamSite/data/en
  label: Data (en)
  create: all
  match: "**/*"
- type: directory
  path: suyamSite/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: suyamSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: suyamSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
